name: hotel_stream
description: A hotel streaming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  video_player: ^2.7.2
  chewie: ^1.7.1
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/ic_new-playstore.png