name: hotel_stream
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: ^2.8.1
  video_player_android: ^2.4.10
  chewie: ^1.7.4
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/videos/
    - assets/images/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated